server:
  port: 8081
spring:
#  redis配置
  redis:
    #地址
    host: 127.0.0.1
#    端口
    port: 6379
#    操作第几个库
    database: 0
  #    password:
  #  redis配置
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reigei
      username: root
      password: 333
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\xiangMuImg\

